### Аналіз California Housing Dataset

California Housing Dataset містить дані про житлові райони Каліфорнії. Кожен рядок описує один район через характеристики населення, будинків і розташування.

#### Практична задача

За характеристиками району передбачити медіанну вартість житла.

#### Dataset

`../data/california_housing.csv`

#### Опис колонок

| Колонка | Що означає | Тип даних | Чи корисна для ML |
|---|---|---|---|
| `MedInc` | медіанний дохід у районі | число | так, це вхідна ознака |
| `HouseAge` | медіанний вік будинків у районі | число | так, це вхідна ознака |
| `AveRooms` | середня кількість кімнат на домогосподарство | число | так, це вхідна ознака |
| `AveBedrms` | середня кількість спалень на домогосподарство | число | так, це вхідна ознака |
| `Population` | населення району | число | так, це вхідна ознака |
| `AveOccup` | середня кількість мешканців на домогосподарство | число | так, це вхідна ознака |
| `Latitude` | географічна широта | число | так, може враховувати розташування |
| `Longitude` | географічна довгота | число | так, може враховувати розташування |
| `MedHouseVal` | медіанна вартість житла | число | так, але як цільова ознака |

In [ ]:
import pandas as pd

In [ ]:
houses_df = pd.read_csv('../../data/california_housing.csv')

In [ ]:
houses_df.head(3)

In [ ]:
houses_df.tail(5)

In [ ]:
houses_df.sample(5)

In [ ]:
houses_df.shape

In [ ]:
houses_df.info()

In [ ]:
houses_df.columns

In [ ]:
houses_df.describe()

In [ ]:
houses_df['MedInc']

In [ ]:
houses_df.head(2)

In [ ]:
houses_df[houses_df['MedInc'] > 8.0]

In [ ]:
houses_df[(houses_df['MedInc'] > 8) | ~(houses_df['HouseAge'] < 20)]

In [ ]:
houses_df.iloc[:6]['HouseAge']

In [ ]:
houses_df.loc[houses_df['HouseAge'] == 52]

In [67]:
df = pd.DataFrame({
    'user_id': [1, 2, 3, 4, 5, 6],
    'Вік': [16, 18, 19, 24, 19, 18],
    'Зарплата': [10000, 20000, 20000, 24000, 40000, 100000]
})

df.head(6)

   user_id  Вік  Зарплата
0        1   16     10000
1        2   18     20000
2        3   19     20000
3        4   24     24000
4        5   19     40000
5        6   18    100000

In [50]:
df.set_index('id', inplace=True)

In [51]:
df

    Вік  Зарплата
id
1    16     10000
2    18     20000
3    19     20000
4    24     24000
5    35     40000
6    39    100000

In [52]:
df.shape

(6, 2)

In [53]:
df.iloc[1]

Вік            18
Зарплата    20000
Name: 2, dtype: int64

In [63]:
df2 = pd.DataFrame({
    'id': [1, 2, 3, 4, 6, 5],
    'name': ['Alex', 'Mark', 'John', 'Irina', 'Olga', 'Valeriy']
})
df2

   id     name
0   1     Alex
1   2     Mark
2   3     John
3   4    Irina
4   6     Olga
5   5  Valeriy

In [57]:
df2.set_index('id', inplace=True)

In [58]:
df2

       name
id
1      Alex
2      Mark
3      John
4     Irina
5      Olga
6   Valeriy

In [64]:
df3 = df.join(df2)
df3

   user_id  Вік  Зарплата  id     name
0        1   16     10000   1     Alex
1        2   18     20000   2     Mark
2        3   19     20000   3     John
3        4   24     24000   4    Irina
4        5   35     40000   6     Olga
5        6   39    100000   5  Valeriy

In [68]:
df4 = df.merge(df2, how='inner', right_on='id', left_on='user_id')
df4

   user_id  Вік  Зарплата  id     name
0        1   16     10000   1     Alex
1        2   18     20000   2     Mark
2        3   19     20000   3     John
3        4   24     24000   4    Irina
4        5   19     40000   5  Valeriy
5        6   18    100000   6     Olga

In [74]:
df4.groupby('Вік')['Зарплата'].count()

Вік
16    1
18    2
19    2
24    1
Name: Зарплата, dtype: int64

In [73]:
df4.groupby('Вік').agg(
    sum_salary=('Зарплата', 'sum'),
    avg_salary=('Зарплата', 'mean')
)

     sum_salary  avg_salary
Вік
16        10000     10000.0
18       120000     60000.0
19        60000     30000.0
24        24000     24000.0