In [1]:
import nltk

nltk.download("movie_reviews")
nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package movie_reviews to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\movie_reviews.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [2]:
from nltk.corpus import movie_reviews
from nltk.tokenize import word_tokenize
import pandas as pd

Отримання списку відгуків

In [3]:
pos_ids = movie_reviews.fileids("pos")[:10]
neg_ids = movie_reviews.fileids("neg")[:10]

selected_ids = pos_ids + neg_ids

Токенізація відгуків

In [4]:
rows = []

for fileid in selected_ids:
    text = movie_reviews.raw(fileid)
    tokens = word_tokenize(text)
    category = fileid.split("/")[0]

    rows.append({
        "fileid": fileid,
        "category": category,
        "token_count": len(tokens),
        "first_20_tokens": tokens[:20],
        "tokens": tokens
    })

df = pd.DataFrame(rows)

df[["fileid", "category", "token_count", "first_20_tokens"]]

,fileid,category,token_count,first_20_tokens
0,pos/cv000_29590.txt,pos,826,"[films, adapted, from, comic, books, have, had..."
1,pos/cv001_18431.txt,pos,786,"[every, now, and, then, a, movie, comes, along..."
2,pos/cv002_15918.txt,pos,476,"[you, 've, got, mail, works, alot, better, tha..."
3,pos/cv003_11664.txt,pos,1197,"[``, jaws, ``, is, a, rare, film, that, grabs,..."
4,pos/cv004_11636.txt,pos,764,"[moviemaking, is, a, lot, like, being, the, ge..."
5,pos/cv005_29443.txt,pos,985,"[on, june, 30, ,, 1960, ,, a, self-taught, ,, ..."
6,pos/cv006_15448.txt,pos,906,"[apparently, ,, director, tony, kaye, had, a, ..."
7,pos/cv007_4968.txt,pos,703,"[one, of, my, colleagues, was, surprised, when..."
8,pos/cv008_29435.txt,pos,310,"[after, bloody, clashes, and, independence, wo..."
9,pos/cv009_29592.txt,pos,489,"[the, american, action, film, has, been, slowl..."
10,neg/cv000_29416.txt,neg,841,"[plot, :, two, teen, couples, go, to, a, churc..."
11,neg/cv001_19502.txt,neg,291,"[the, happy, bastard, 's, quick, movie, review..."
12,neg/cv002_17424.txt,neg,562,"[it, is, movies, like, these, that, make, a, j..."
13,neg/cv003_12683.txt,neg,574,"[``, quest, for, camelot, ``, is, warner, bros..."
14,neg/cv004_12641.txt,neg,855,"[synopsis, :, a, mentally, unstable, man, unde..."
15,neg/cv005_29357.txt,neg,748,"[capsule, :, in, 2176, on, the, planet, mars, ..."
16,neg/cv006_17022.txt,neg,656,"[so, ask, yourself, what, ``, 8mm, ``, (, ``, ..."
17,neg/cv007_4992.txt,neg,689,"[that, 's, exactly, how, long, the, movie, fel..."
18,neg/cv008_29326.txt,neg,820,"[call, it, a, road, trip, for, the, walking, w..."
19,neg/cv009_29417.txt,neg,971,"[plot, :, a, young, french, boy, sees, his, pa..."

Якщо first_20_tokens важко читати в таблиці

In [5]:
df["first_20_tokens_text"] = df["first_20_tokens"].apply(lambda tokens: " ".join(tokens))

df[["fileid", "category", "token_count", "first_20_tokens_text"]]

,fileid,category,token_count,first_20_tokens_text
0,pos/cv000_29590.txt,pos,826,films adapted from comic books have had plenty...
1,pos/cv001_18431.txt,pos,786,every now and then a movie comes along from a ...
2,pos/cv002_15918.txt,pos,476,you 've got mail works alot better than it des...
3,pos/cv003_11664.txt,pos,1197,`` jaws `` is a rare film that grabs your atte...
4,pos/cv004_11636.txt,pos,764,moviemaking is a lot like being the general ma...
5,pos/cv005_29443.txt,pos,985,"on june 30 , 1960 , a self-taught , idealistic..."
6,pos/cv006_15448.txt,pos,906,"apparently , director tony kaye had a major ba..."
7,pos/cv007_4968.txt,pos,703,one of my colleagues was surprised when i told...
8,pos/cv008_29435.txt,pos,310,"after bloody clashes and independence won , lu..."
9,pos/cv009_29592.txt,pos,489,the american action film has been slowly drown...
10,neg/cv000_29416.txt,neg,841,"plot : two teen couples go to a church party ,..."
11,neg/cv001_19502.txt,neg,291,the happy bastard 's quick movie review damn t...
12,neg/cv002_17424.txt,neg,562,it is movies like these that make a jaded movi...
13,neg/cv003_12683.txt,neg,574,`` quest for camelot `` is warner bros . ' fir...
14,neg/cv004_12641.txt,neg,855,synopsis : a mentally unstable man undergoing ...
15,neg/cv005_29357.txt,neg,748,capsule : in 2176 on the planet mars police ta...
16,neg/cv006_17022.txt,neg,656,so ask yourself what `` 8mm `` ( `` eight mill...
17,neg/cv007_4992.txt,neg,689,that 's exactly how long the movie felt to me ...
18,neg/cv008_29326.txt,neg,820,call it a road trip for the walking wounded . ...
19,neg/cv009_29417.txt,neg,971,plot : a young french boy sees his parents kil...

Базова статистика

In [6]:
total_tokens = df["token_count"].sum()
avg_tokens = df["token_count"].mean()
min_tokens = df["token_count"].min()
max_tokens = df["token_count"].max()

print("Загальна кількість токенів:", total_tokens)
print("Середня кількість токенів:", avg_tokens)
print("Мінімальна довжина:", min_tokens)
print("Максимальна довжина:", max_tokens)

Загальна кількість токенів: 14449
Середня кількість токенів: 722.45
Мінімальна довжина: 291
Максимальна довжина: 1197

Середня довжина позитивних і негативних відгуків

In [7]:
df.groupby("category")["token_count"].mean()

category
neg    700.7
pos    744.2
Name: token_count, dtype: float64

Зібрати всі токени

In [8]:
all_tokens = [token for tokens in df["tokens"] for token in tokens]

 перші 30 токенів, які не складаються тільки з літер:

In [9]:
strange_tokens = [token for token in all_tokens if not token.isalpha()]

strange_tokens[:30]

[',',
 "'re",
 '(',
 ',',
 ',',
 ')',
 ',',
 '(',
 ')',
 '(',
 ')',
 ',',
 "'s",
 '.',
 ',',
 '(',
 ')',
 ',',
 "'80s",
 '12-part',
 '.',
 '.',
 '(',
 '``',
 ',',
 '``',
 ')',
 '500',
 '30',
 '.']

які такі токени трапляються найчастіше:

In [10]:
from collections import Counter

Counter(strange_tokens).most_common(20)

[(',', 831),
 ('.', 574),
 ("'s", 216),
 ('``', 162),
 ('(', 127),
 (')', 126),
 ("n't", 66),
 ('?', 52),
 ('--', 27),
 (':', 26),
 ('!', 18),
 ('-', 16),
 ("'ve", 14),
 ("'", 12),
 ("'re", 8),
 ('2', 7),
 ('_election_', 7),
 ('_rushmore_', 6),
 ('&', 6),
 ('8mm', 6)]